#!/bin/bash
origdir=$(pwd)
runfile=$(readlink -f "$0") # becaue we might be called via symlink
scd=$(dirname "$runfile")
sc=$(basename "$scd")
cd "$scd" || exit 1

if test -f md5.txt; then
#  echo "md5.txt exists, copying to old_md5.txt"
  mv md5.txt old_md5.txt
fi

find src build.gradle.kts -type f -exec md5 '{}' \; > md5.txt

if !(test -f old_md5.txt) || !(diff old_md5.txt md5.txt 1>/dev/null); then
  # echo "changes!!"
  >&2 echo "Compiling... (future runs will be faster)"
  # echo -n | gradle is so that gradle won't swallow stdin, leaving it available for the script
  if echo -n | ./gradlew shadowJar --warning-mode none 1>/dev/null; then
      echo "Success!"
  else
      rm md5.txt
      exit 1
  fi
# else
  # echo "no changes!"
fi

if test -f old_md5.txt; then
    rm old_md5.txt
fi

cd $origdir
SCRIPT_DIR=$scd java -jar $scd/build/libs/$sc-all.jar "$@"
